// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.deleteRefreshTokenStmt, err = db.PrepareContext(ctx, deleteRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRefreshToken: %w", err)
	}
	if q.getRefreshTokensByUserIDStmt, err = db.PrepareContext(ctx, getRefreshTokensByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetRefreshTokensByUserID: %w", err)
	}
	if q.invalidateRefreshTokenStmt, err = db.PrepareContext(ctx, invalidateRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query InvalidateRefreshToken: %w", err)
	}
	if q.revokeAllUserSessionsStmt, err = db.PrepareContext(ctx, revokeAllUserSessions); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeAllUserSessions: %w", err)
	}
	if q.revokeSessionStmt, err = db.PrepareContext(ctx, revokeSession); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeSession: %w", err)
	}
	if q.validateSessionStmt, err = db.PrepareContext(ctx, validateSession); err != nil {
		return nil, fmt.Errorf("error preparing query ValidateSession: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.deleteRefreshTokenStmt != nil {
		if cerr := q.deleteRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRefreshTokenStmt: %w", cerr)
		}
	}
	if q.getRefreshTokensByUserIDStmt != nil {
		if cerr := q.getRefreshTokensByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRefreshTokensByUserIDStmt: %w", cerr)
		}
	}
	if q.invalidateRefreshTokenStmt != nil {
		if cerr := q.invalidateRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing invalidateRefreshTokenStmt: %w", cerr)
		}
	}
	if q.revokeAllUserSessionsStmt != nil {
		if cerr := q.revokeAllUserSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeAllUserSessionsStmt: %w", cerr)
		}
	}
	if q.revokeSessionStmt != nil {
		if cerr := q.revokeSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeSessionStmt: %w", cerr)
		}
	}
	if q.validateSessionStmt != nil {
		if cerr := q.validateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing validateSessionStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                           DBTX
	tx                           *sql.Tx
	createSessionStmt            *sql.Stmt
	deleteRefreshTokenStmt       *sql.Stmt
	getRefreshTokensByUserIDStmt *sql.Stmt
	invalidateRefreshTokenStmt   *sql.Stmt
	revokeAllUserSessionsStmt    *sql.Stmt
	revokeSessionStmt            *sql.Stmt
	validateSessionStmt          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                           tx,
		tx:                           tx,
		createSessionStmt:            q.createSessionStmt,
		deleteRefreshTokenStmt:       q.deleteRefreshTokenStmt,
		getRefreshTokensByUserIDStmt: q.getRefreshTokensByUserIDStmt,
		invalidateRefreshTokenStmt:   q.invalidateRefreshTokenStmt,
		revokeAllUserSessionsStmt:    q.revokeAllUserSessionsStmt,
		revokeSessionStmt:            q.revokeSessionStmt,
		validateSessionStmt:          q.validateSessionStmt,
	}
}
