// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuthSession struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.NullUUID  `json:"user_id"`
	CreatedAt      time.Time      `json:"created_at"`
	ExpiresAt      time.Time      `json:"expires_at"`
	LastAccessedAt sql.NullTime   `json:"last_accessed_at"`
	RevokedAt      sql.NullTime   `json:"revoked_at"`
	UserAgent      sql.NullString `json:"user_agent"`
	IpAddress      sql.NullString `json:"ip_address"`
}

type AuthUser struct {
	ID                         uuid.UUID      `json:"id"`
	Email                      string         `json:"email"`
	PasswordHash               string         `json:"password_hash"`
	EmailConfirmedAt           sql.NullTime   `json:"email_confirmed_at"`
	ConfirmationToken          sql.NullString `json:"confirmation_token"`
	ConfirmationTokenCreatedAt sql.NullTime   `json:"confirmation_token_created_at"`
	EmailChange                sql.NullString `json:"email_change"`
	EmailChangeToken           sql.NullString `json:"email_change_token"`
	EmailChangeRequestedAt     sql.NullTime   `json:"email_change_requested_at"`
	PasswordChange             sql.NullString `json:"password_change"`
	PasswordChangeToken        sql.NullString `json:"password_change_token"`
	PasswordChangeRequestedAt  sql.NullTime   `json:"password_change_requested_at"`
	EncryptedOtp               sql.NullString `json:"encrypted_otp"`
	OtpCreatedAt               sql.NullTime   `json:"otp_created_at"`
	CreatedAt                  time.Time      `json:"created_at"`
	UpdatedAt                  time.Time      `json:"updated_at"`
	DeletedAt                  sql.NullTime   `json:"deleted_at"`
}
