// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error)
	RevokeAllUserSessions(ctx context.Context, userID uuid.NullUUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	ValidateSession(ctx context.Context, id uuid.UUID) (AuthSession, error)
}

var _ Querier = (*Queries)(nil)
