// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
insert into auth.sessions (user_id, expires_at, ip_address) 
values ($1, $2, $3)
returning id, user_id, created_at, expires_at, last_accessed_at, revoked_at, user_agent, ip_address
`

type CreateSessionParams struct {
	UserID    uuid.NullUUID  `json:"user_id"`
	ExpiresAt time.Time      `json:"expires_at"`
	IpAddress sql.NullString `json:"ip_address"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error) {
	row := q.queryRow(ctx, q.createSessionStmt, createSession, arg.UserID, arg.ExpiresAt, arg.IpAddress)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastAccessedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddress,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
update auth.sessions set revoked_at = now() where user_id = $1
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.NullUUID) error {
	_, err := q.exec(ctx, q.revokeAllUserSessionsStmt, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
update auth.sessions set revoked_at = now() where id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.revokeSessionStmt, revokeSession, id)
	return err
}

const validateSession = `-- name: ValidateSession :one
select id, user_id, created_at, expires_at, last_accessed_at, revoked_at, user_agent, ip_address from auth.sessions where id = $1 and revoked_at is null
`

func (q *Queries) ValidateSession(ctx context.Context, id uuid.UUID) (AuthSession, error) {
	row := q.queryRow(ctx, q.validateSessionStmt, validateSession, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastAccessedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddress,
	)
	return i, err
}
