// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.completeEmailUpdateStmt, err = db.PrepareContext(ctx, completeEmailUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query CompleteEmailUpdate: %w", err)
	}
	if q.completePasswordResetStmt, err = db.PrepareContext(ctx, completePasswordReset); err != nil {
		return nil, fmt.Errorf("error preparing query CompletePasswordReset: %w", err)
	}
	if q.completePasswordUpdateStmt, err = db.PrepareContext(ctx, completePasswordUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query CompletePasswordUpdate: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteUserByIdStmt, err = db.PrepareContext(ctx, deleteUserById); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUserById: %w", err)
	}
	if q.getPasswordHashStmt, err = db.PrepareContext(ctx, getPasswordHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetPasswordHash: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserByPasswordChangeTokenStmt, err = db.PrepareContext(ctx, getUserByPasswordChangeToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByPasswordChangeToken: %w", err)
	}
	if q.initiateEmailUpdateStmt, err = db.PrepareContext(ctx, initiateEmailUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query InitiateEmailUpdate: %w", err)
	}
	if q.initiatePasswordResetStmt, err = db.PrepareContext(ctx, initiatePasswordReset); err != nil {
		return nil, fmt.Errorf("error preparing query InitiatePasswordReset: %w", err)
	}
	if q.initiatePasswordUpdateStmt, err = db.PrepareContext(ctx, initiatePasswordUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query InitiatePasswordUpdate: %w", err)
	}
	if q.setUserSignupAsConfirmedStmt, err = db.PrepareContext(ctx, setUserSignupAsConfirmed); err != nil {
		return nil, fmt.Errorf("error preparing query SetUserSignupAsConfirmed: %w", err)
	}
	if q.softDeleteUserByIdStmt, err = db.PrepareContext(ctx, softDeleteUserById); err != nil {
		return nil, fmt.Errorf("error preparing query SoftDeleteUserById: %w", err)
	}
	if q.userExistsStmt, err = db.PrepareContext(ctx, userExists); err != nil {
		return nil, fmt.Errorf("error preparing query UserExists: %w", err)
	}
	if q.userExistsWithEmailStmt, err = db.PrepareContext(ctx, userExistsWithEmail); err != nil {
		return nil, fmt.Errorf("error preparing query UserExistsWithEmail: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.completeEmailUpdateStmt != nil {
		if cerr := q.completeEmailUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing completeEmailUpdateStmt: %w", cerr)
		}
	}
	if q.completePasswordResetStmt != nil {
		if cerr := q.completePasswordResetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing completePasswordResetStmt: %w", cerr)
		}
	}
	if q.completePasswordUpdateStmt != nil {
		if cerr := q.completePasswordUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing completePasswordUpdateStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteUserByIdStmt != nil {
		if cerr := q.deleteUserByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserByIdStmt: %w", cerr)
		}
	}
	if q.getPasswordHashStmt != nil {
		if cerr := q.getPasswordHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPasswordHashStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserByPasswordChangeTokenStmt != nil {
		if cerr := q.getUserByPasswordChangeTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByPasswordChangeTokenStmt: %w", cerr)
		}
	}
	if q.initiateEmailUpdateStmt != nil {
		if cerr := q.initiateEmailUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing initiateEmailUpdateStmt: %w", cerr)
		}
	}
	if q.initiatePasswordResetStmt != nil {
		if cerr := q.initiatePasswordResetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing initiatePasswordResetStmt: %w", cerr)
		}
	}
	if q.initiatePasswordUpdateStmt != nil {
		if cerr := q.initiatePasswordUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing initiatePasswordUpdateStmt: %w", cerr)
		}
	}
	if q.setUserSignupAsConfirmedStmt != nil {
		if cerr := q.setUserSignupAsConfirmedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setUserSignupAsConfirmedStmt: %w", cerr)
		}
	}
	if q.softDeleteUserByIdStmt != nil {
		if cerr := q.softDeleteUserByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing softDeleteUserByIdStmt: %w", cerr)
		}
	}
	if q.userExistsStmt != nil {
		if cerr := q.userExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userExistsStmt: %w", cerr)
		}
	}
	if q.userExistsWithEmailStmt != nil {
		if cerr := q.userExistsWithEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userExistsWithEmailStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	completeEmailUpdateStmt          *sql.Stmt
	completePasswordResetStmt        *sql.Stmt
	completePasswordUpdateStmt       *sql.Stmt
	createUserStmt                   *sql.Stmt
	deleteUserByIdStmt               *sql.Stmt
	getPasswordHashStmt              *sql.Stmt
	getUserByEmailStmt               *sql.Stmt
	getUserByIDStmt                  *sql.Stmt
	getUserByPasswordChangeTokenStmt *sql.Stmt
	initiateEmailUpdateStmt          *sql.Stmt
	initiatePasswordResetStmt        *sql.Stmt
	initiatePasswordUpdateStmt       *sql.Stmt
	setUserSignupAsConfirmedStmt     *sql.Stmt
	softDeleteUserByIdStmt           *sql.Stmt
	userExistsStmt                   *sql.Stmt
	userExistsWithEmailStmt          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		completeEmailUpdateStmt:          q.completeEmailUpdateStmt,
		completePasswordResetStmt:        q.completePasswordResetStmt,
		completePasswordUpdateStmt:       q.completePasswordUpdateStmt,
		createUserStmt:                   q.createUserStmt,
		deleteUserByIdStmt:               q.deleteUserByIdStmt,
		getPasswordHashStmt:              q.getPasswordHashStmt,
		getUserByEmailStmt:               q.getUserByEmailStmt,
		getUserByIDStmt:                  q.getUserByIDStmt,
		getUserByPasswordChangeTokenStmt: q.getUserByPasswordChangeTokenStmt,
		initiateEmailUpdateStmt:          q.initiateEmailUpdateStmt,
		initiatePasswordResetStmt:        q.initiatePasswordResetStmt,
		initiatePasswordUpdateStmt:       q.initiatePasswordUpdateStmt,
		setUserSignupAsConfirmedStmt:     q.setUserSignupAsConfirmedStmt,
		softDeleteUserByIdStmt:           q.softDeleteUserByIdStmt,
		userExistsStmt:                   q.userExistsStmt,
		userExistsWithEmailStmt:          q.userExistsWithEmailStmt,
	}
}
