// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CompleteEmailUpdate(ctx context.Context, id uuid.UUID) error
	CompletePasswordUpdate(ctx context.Context, id uuid.UUID) error
	CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error)
	DeleteUserById(ctx context.Context, id uuid.UUID) (AuthUser, error)
	GetPasswordHash(ctx context.Context, id uuid.UUID) (string, error)
	GetUserByEmail(ctx context.Context, email string) (AuthUser, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error)
	InitiateEmailUpdate(ctx context.Context, arg InitiateEmailUpdateParams) error
	InitiatePasswordUpdate(ctx context.Context, arg InitiatePasswordUpdateParams) error
	SetUserSignupAdConfirmed(ctx context.Context, id uuid.UUID) error
	SoftDeleteUserById(ctx context.Context, id uuid.UUID) (AuthUser, error)
	UserExists(ctx context.Context, id uuid.UUID) (bool, error)
	UserExistsWithEmail(ctx context.Context, email string) (bool, error)
}

var _ Querier = (*Queries)(nil)
