// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const completeEmailUpdate = `-- name: CompleteEmailUpdate :exec
update auth.users
set email = email_change,
    email_change = null,
    email_change_token = null,
    encrypted_otp = null,
    otp_created_at = null
where id = $1
`

func (q *Queries) CompleteEmailUpdate(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.completeEmailUpdateStmt, completeEmailUpdate, id)
	return err
}

const completePasswordUpdate = `-- name: CompletePasswordUpdate :exec
update auth.users
set password_hash = password_change,
    password_change = null,
    password_change_token = null,
    password_change_requested_at = null
where id = $1
`

func (q *Queries) CompletePasswordUpdate(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.completePasswordUpdateStmt, completePasswordUpdate, id)
	return err
}

const createUser = `-- name: CreateUser :one
insert into auth.users (email, password_hash, confirmation_token, confirmation_token_created_at) 
values ($1, $2, $3, now()) 
returning id, email, password_hash, email_confirmed_at, confirmation_token, confirmation_token_created_at, email_change, email_change_token, email_change_requested_at, password_change, password_change_token, password_change_requested_at, encrypted_otp, otp_created_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email             string         `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	ConfirmationToken sql.NullString `json:"confirmation_token"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Email, arg.PasswordHash, arg.ConfirmationToken)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailConfirmedAt,
		&i.ConfirmationToken,
		&i.ConfirmationTokenCreatedAt,
		&i.EmailChange,
		&i.EmailChangeToken,
		&i.EmailChangeRequestedAt,
		&i.PasswordChange,
		&i.PasswordChangeToken,
		&i.PasswordChangeRequestedAt,
		&i.EncryptedOtp,
		&i.OtpCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUserById = `-- name: DeleteUserById :one
delete from auth.users where id = $1 returning id, email, password_hash, email_confirmed_at, confirmation_token, confirmation_token_created_at, email_change, email_change_token, email_change_requested_at, password_change, password_change_token, password_change_requested_at, encrypted_otp, otp_created_at, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteUserById(ctx context.Context, id uuid.UUID) (AuthUser, error) {
	row := q.queryRow(ctx, q.deleteUserByIdStmt, deleteUserById, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailConfirmedAt,
		&i.ConfirmationToken,
		&i.ConfirmationTokenCreatedAt,
		&i.EmailChange,
		&i.EmailChangeToken,
		&i.EmailChangeRequestedAt,
		&i.PasswordChange,
		&i.PasswordChangeToken,
		&i.PasswordChangeRequestedAt,
		&i.EncryptedOtp,
		&i.OtpCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPasswordHash = `-- name: GetPasswordHash :one
select password_hash from auth.users where id = $1 limit 1
`

func (q *Queries) GetPasswordHash(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.queryRow(ctx, q.getPasswordHashStmt, getPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_hash, email_confirmed_at, confirmation_token, confirmation_token_created_at, email_change, email_change_token, email_change_requested_at, password_change, password_change_token, password_change_requested_at, encrypted_otp, otp_created_at, created_at, updated_at, deleted_at from auth.users where email = $1 and deleted_at is null limit 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailConfirmedAt,
		&i.ConfirmationToken,
		&i.ConfirmationTokenCreatedAt,
		&i.EmailChange,
		&i.EmailChangeToken,
		&i.EmailChangeRequestedAt,
		&i.PasswordChange,
		&i.PasswordChangeToken,
		&i.PasswordChangeRequestedAt,
		&i.EncryptedOtp,
		&i.OtpCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email, password_hash, email_confirmed_at, confirmation_token, confirmation_token_created_at, email_change, email_change_token, email_change_requested_at, password_change, password_change_token, password_change_requested_at, encrypted_otp, otp_created_at, created_at, updated_at, deleted_at from auth.users where id = $1 and deleted_at is null
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailConfirmedAt,
		&i.ConfirmationToken,
		&i.ConfirmationTokenCreatedAt,
		&i.EmailChange,
		&i.EmailChangeToken,
		&i.EmailChangeRequestedAt,
		&i.PasswordChange,
		&i.PasswordChangeToken,
		&i.PasswordChangeRequestedAt,
		&i.EncryptedOtp,
		&i.OtpCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const initiateEmailUpdate = `-- name: InitiateEmailUpdate :exec
update auth.users 
set email_change = $1, 
    email_change_token = $2,
    email_change_requested_at = now(),
    encrypted_otp = $3,
    otp_created_at = now()
where id = $4
`

type InitiateEmailUpdateParams struct {
	EmailChange      sql.NullString `json:"email_change"`
	EmailChangeToken sql.NullString `json:"email_change_token"`
	EncryptedOtp     sql.NullString `json:"encrypted_otp"`
	ID               uuid.UUID      `json:"id"`
}

func (q *Queries) InitiateEmailUpdate(ctx context.Context, arg InitiateEmailUpdateParams) error {
	_, err := q.exec(ctx, q.initiateEmailUpdateStmt, initiateEmailUpdate,
		arg.EmailChange,
		arg.EmailChangeToken,
		arg.EncryptedOtp,
		arg.ID,
	)
	return err
}

const initiatePasswordUpdate = `-- name: InitiatePasswordUpdate :exec
update auth.users
set password_change = $1,
    password_change_token = $2,
    password_change_requested_at = now(),
    encrypted_otp = $3,
    otp_created_at = now()
where id = $4
`

type InitiatePasswordUpdateParams struct {
	PasswordChange      sql.NullString `json:"password_change"`
	PasswordChangeToken sql.NullString `json:"password_change_token"`
	EncryptedOtp        sql.NullString `json:"encrypted_otp"`
	ID                  uuid.UUID      `json:"id"`
}

func (q *Queries) InitiatePasswordUpdate(ctx context.Context, arg InitiatePasswordUpdateParams) error {
	_, err := q.exec(ctx, q.initiatePasswordUpdateStmt, initiatePasswordUpdate,
		arg.PasswordChange,
		arg.PasswordChangeToken,
		arg.EncryptedOtp,
		arg.ID,
	)
	return err
}

const setUserSignupAdConfirmed = `-- name: SetUserSignupAdConfirmed :exec
update auth.users
set confirmation_token = null,
    confirmation_token_created_at = null,
    email_confirmed_at = now()
where id = $1
`

func (q *Queries) SetUserSignupAdConfirmed(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.setUserSignupAdConfirmedStmt, setUserSignupAdConfirmed, id)
	return err
}

const softDeleteUserById = `-- name: SoftDeleteUserById :one
update auth.users set deleted_at = now() where id = $1 returning id, email, password_hash, email_confirmed_at, confirmation_token, confirmation_token_created_at, email_change, email_change_token, email_change_requested_at, password_change, password_change_token, password_change_requested_at, encrypted_otp, otp_created_at, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteUserById(ctx context.Context, id uuid.UUID) (AuthUser, error) {
	row := q.queryRow(ctx, q.softDeleteUserByIdStmt, softDeleteUserById, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailConfirmedAt,
		&i.ConfirmationToken,
		&i.ConfirmationTokenCreatedAt,
		&i.EmailChange,
		&i.EmailChangeToken,
		&i.EmailChangeRequestedAt,
		&i.PasswordChange,
		&i.PasswordChangeToken,
		&i.PasswordChangeRequestedAt,
		&i.EncryptedOtp,
		&i.OtpCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
select exists (select 1 from auth.users where id = $1)
`

func (q *Queries) UserExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.queryRow(ctx, q.userExistsStmt, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userExistsWithEmail = `-- name: UserExistsWithEmail :one
select exists (select 1 from auth.users where email = $1)
`

func (q *Queries) UserExistsWithEmail(ctx context.Context, email string) (bool, error) {
	row := q.queryRow(ctx, q.userExistsWithEmailStmt, userExistsWithEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
